<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('transaksi')->insert([
            [
                'id' => 1,
                'total_harga' => 50000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 60000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:08:18',
                'updated_at' => '2025-05-17 19:08:18',
            ],
            [
                'id' => 2,
                'total_harga' => 50000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 60000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:08:21',
                'updated_at' => '2025-05-17 19:08:21',
            ],
            [
                'id' => 3,
                'total_harga' => 50000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 60000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:08:23',
                'updated_at' => '2025-05-17 19:08:23',
            ],
            [
                'id' => 4,
                'total_harga' => 50000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 60000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:08:26',
                'updated_at' => '2025-05-17 19:08:26',
            ],
            [
                'id' => 5,
                'total_harga' => 50000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 60000.00,
                'metode_pembayaran' => 'qris',
                'nomor_resi' => NULL,
                'status_pembayaran' => 'expired',
                'status_pengiriman' => 'diterima',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => 'c4254e8c-4394-45c0-a551-fcb6622ec60c',
                'midtrans_order_id' => 'TRX-5',
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:08:29',
                'updated_at' => '2025-05-20 00:04:16',
            ],
            [
                'id' => 6,
                'total_harga' => 20000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 30000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:09:39',
                'updated_at' => '2025-05-17 19:09:39',
            ],
            [
                'id' => 7,
                'total_harga' => 20000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 30000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:09:41',
                'updated_at' => '2025-05-17 19:09:41',
            ],
            [
                'id' => 8,
                'total_harga' => 20000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 30000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 19:09:44',
                'updated_at' => '2025-05-17 19:09:44',
            ],
            [
                'id' => 9,
                'total_harga' => 30000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 40000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 20:07:30',
                'updated_at' => '2025-05-17 20:07:30',
            ],
            [
                'id' => 10,
                'total_harga' => 30000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 40000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 20:07:34',
                'updated_at' => '2025-05-17 20:07:34',
            ],
            [
                'id' => 11,
                'total_harga' => 30000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 40000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 20:07:38',
                'updated_at' => '2025-05-17 20:07:38',
            ],
            [
                'id' => 12,
                'total_harga' => 30000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 40000.00,
                'metode_pembayaran' => NULL,
                'nomor_resi' => NULL,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => NULL,
                'midtrans_order_id' => NULL,
                'akun_id' => 2,
                'created_at' => '2025-05-17 20:07:41',
                'updated_at' => '2025-05-17 20:07:41',
            ],
            [
                'id' => 13,
                'total_harga' => 30000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 40000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => 'nsyf23356',
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'diterima',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => 'd0788f32-83c9-49de-8fa7-568e07a114c4',
                'midtrans_order_id' => 'TRX-13',
                'akun_id' => 2,
                'created_at' => '2025-05-17 20:07:45',
                'updated_at' => '2025-05-17 20:10:03',
            ],
            [
                'id' => 14,
                'total_harga' => 10000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 20000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => NULL,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'diterima',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => '72c7231a-94d1-4f3d-9091-5b8fd257138e',
                'midtrans_order_id' => 'TRX-14',
                'akun_id' => 2,
                'created_at' => '2025-05-17 20:11:24',
                'updated_at' => '2025-05-17 20:13:13',
            ],
            [
                'id' => 16,
                'total_harga' => 20000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 30000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => NULL,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'diterima',
                'alamat_pengiriman' => '{"detail_alamat":"583 Kacey Stravenue Apt. 593\\nNorth Demarcusside, AR 49578-8302","kelurahan":"molestiae","kecamatan":"accusamus","kabupaten":"","provinsi":"New Jersey","no_hp":""}',
                'snap_token' => 'ddda7b46-da27-403e-a8cc-4c68348b4681',
                'midtrans_order_id' => 'TRX-16',
                'akun_id' => 2,
                'created_at' => '2025-05-21 14:37:20',
                'updated_at' => '2025-05-21 14:38:11',
            ],
            [
                'id' => 17,
                'total_harga' => 60000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 70000.00,
                'metode_pembayaran' => null,
                'nomor_resi' => null,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => null,
                'midtrans_order_id' => null,
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 3, 22, 19, 28, 12),
                'updated_at' => Carbon::create(2025, 5, 22, 19, 28, 12),
            ],
            [
                'id' => 18,
                'total_harga' => 60000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 70000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'diterima',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '34696938-99fa-4125-9eab-51dd85f85865',
                'midtrans_order_id' => 'TRX-18',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 3, 22, 19, 28, 28),
                'updated_at' => Carbon::create(2025, 5, 22, 19, 30, 47),
            ],
            [
                'id' => 19,
                'total_harga' => 20000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 30000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => 'eebaec1c-ae66-4a6b-b0fc-fcc757a2a7a7',
                'midtrans_order_id' => 'TRX-19',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 3, 22, 19, 37, 33),
                'updated_at' => Carbon::create(2025, 5, 22, 19, 38, 15),
            ],
            [
                'id' => 20,
                'total_harga' => 15000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => null,
                'nomor_resi' => null,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '49137e92-a891-4795-827e-b36b7242433f',
                'midtrans_order_id' => 'TRX-20',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 4, 22, 19, 40, 5),
                'updated_at' => Carbon::create(2025, 5, 22, 19, 40, 6),
            ],
            [
                'id' => 21,
                'total_harga' => 45000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 55000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => 'nsyf23356',
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '62cd6513-8195-4457-b231-fdebc021ff6f',
                'midtrans_order_id' => 'TRX-21',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 4, 22, 19, 49, 24),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 35, 44),
            ],
            [
                'id' => 22,
                'total_harga' => 45000.00,
                'biaya_pengiriman' => 18000.00,
                'total_bayar' => 55000.00,
                'metode_pembayaran' => null,
                'nomor_resi' => null,
                'status_pembayaran' => 'pending',
                'status_pengiriman' => 'dikemas',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-22',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 4, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
            [
                'id' => 23,
                'total_harga' => 25000.00,
                'biaya_pengiriman' => 00.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikirim',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-23',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 4, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
            [
                'id' => 24,
                'total_harga' => 25000.00,
                'biaya_pengiriman' => 00.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikirim',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-23',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 6, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
            [
                'id' => 25,
                'total_harga' => 25000.00,
                'biaya_pengiriman' => 00.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikirim',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-23',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 6, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
            [
                'id' => 26,
                'total_harga' => 25000.00,
                'biaya_pengiriman' => 00.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikirim',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-23',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 4, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
            [
                'id' => 27,
                'total_harga' => 25000.00,
                'biaya_pengiriman' => 00.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikirim',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-23',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 5, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
            [
                'id' => 28,
                'total_harga' => 25000.00,
                'biaya_pengiriman' => 00.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikirim',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-23',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 6, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
            [
                'id' => 29,
                'total_harga' => 25000.00,
                'biaya_pengiriman' => 00.00,
                'total_bayar' => 25000.00,
                'metode_pembayaran' => 'bank_transfer',
                'nomor_resi' => null,
                'status_pembayaran' => 'success',
                'status_pengiriman' => 'dikirim',
                'alamat_pengiriman' => '{"detail_alamat":"147 Lesch Haven Suite 251\\nNorth Larry, NE 14569","kelurahan":"atque","kecamatan":"unde","kabupaten":"","provinsi":"New York","no_hp":""}',
                'snap_token' => '46136aa1-7cf6-4d15-a72d-add4401a6b5f',
                'midtrans_order_id' => 'TRX-23',
                'akun_id' => 2,
                'created_at' => Carbon::create(2025, 6, 23, 20, 23, 32),
                'updated_at' => Carbon::create(2025, 5, 23, 20, 23, 37),
            ],
        ]);
    }
}
